version: '2'
services:
  db:
    image: mysql:latest
    volumes:
      - "./data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "!changeit!"
      MYSQL_DATABASE: pydiodb
      MYSQL_USER: pydiouser
      MYSQL_PASSWORD: "changeit"

  web:
    build: pydio
    environment:
      SERVERNAME: "yourservername"
    links:
      - db:dbserver
    ports:
      - "8080:80"
      - "8443:8443"
    volumes:
      - "./pydio/etc/httpd/conf:/etc/httpd/conf"
      - "./pydio/etc/httpd/conf.d:/etc/httpd/conf.d"
      - "./pydio/etc/httpd/ssl.crt:/etc/httpd/ssl.crt"
      - "./pydio/etc/pydio:/etc/pydio"
      - "./data/running-app/pydio:/var/lib/pydio/plugins/boot.conf"
      - "./data/running-app/cache:/var/cache/pydio/"
      - "./data/files:/var/lib/pydio/files/"
      - "./data/personal:/var/lib/pydio/personal"
      - "./data/public:/var/lib/pydio/public"
